default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.16.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus"]
        exclude_types: ["html", "csv"]
  - repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
      - id: black
        description: "Black formatting"
        exclude_types: ["html", "csv"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        description: "Trims trailing whitespace"
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        description: "Makes sure files end in a newline and only a newline."
      - id: debug-statements
        description: "Check for debugger imports and breakpoints"
      - id: check-docstring-first
        description: "Checks for a common error of placing code before the docstring"
      - id: check-merge-conflict
        description: "Check for files that contain merge conflict strings"
      - id: mixed-line-ending
        description: "Replaces or checks mixed line endings"
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-case-conflict
        exclude_types: ["html", "csv"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.0"
    hooks:
      - id: prettier
        exclude_types: ["html", "csv"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        exclude_types: ["html", "csv"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests, --skip, "B101", --recursive, clumper]
        files: .py$
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-check-mock-methods
      - id: python-check-blanket-noqa
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
