version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: sh startserver.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.tpl
    depends_on:
      - db
