# Generated by Django 3.2.8 on 2021-10-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_remove_movie_avis"),
        ("review", "0002_alter_review_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
    ]
