# Generated by Django 3.2.8 on 2021-10-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_avis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="avis",
        ),
    ]
